### ISSUE TITLE
idek just a random issue

### ISSUE THREAD

**Issue by DeratonTrix** [xharky/Nitro-Promo-codes-gen#1]
![unknown](https://user-images.githubusercontent.com/94805186/182707923-49818b20-bd9d-4abc-9dd7-2050b0d74ffe.png)

**Comment by Lazoeak** [comment]
same

**Comment by ohlunaaa** [comment]
the token needs to be mail verified and 1 month old

**Comment by DeratonTrix** [comment]
> the token needs to be mail verified and 1 month old

damn why 1 month old that kinda sucks ngl

**Comment by Najmul190** [comment]
> the token needs to be mail verified and 1 month old

still doesnt work

**Comment by Roywesley** [comment]
Verifyed email and 5 y old accounts, dznt work

**Comment by ohlunaaa** [comment]
Patched
